### ISSUE TITLE
Add git packages

### ISSUE THREAD

**Issue by xfalcox** [torba-rb/torba#35]
What about adding git repositories as an option? 

This would be useful to handle internal git repository, gitlab repos and so. 

We can use shallow clones to speed up.

**Comment by nashbridges** [comment]
I don't mind supporting git as another remote source.

However, this is not a high priority task for me, since every popular asset project is published on npm. Furthemore, I could find a small amount of git repos which contain *built* (compiled) assets.

Your comment for private git repos is valid though.

**Comment by xfalcox** [comment]
We have a bunch of internal reusable front end assets, all hosted on gitlab, and git would enable to use then. 

Like react components and sass files.

**Comment by JanStevens** [comment]
You know you can create from every branch / tag a zip package in gitlab?

**Comment by nashbridges** [comment]
@xfalcox will current Gitlab functionality (download a zip archive) be enough for you? If so, I prefer not to add this feature until absolutely necessary.

**Comment by xfalcox** [comment]
@nashbridges Actually no, but I can use my fork of the gem then.

Thanks!
